// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

import 'package:template_project/model/test_model.dart';
import 'package:ff_annotation_route_library/ff_annotation_route_library.dart';
import 'package:flutter/widgets.dart';
import '../page/home/home_page.dart';
import '../page/home/test_page.dart';

// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import
FFRouteSettings getRouteSettings({
  required String name,
  Map<String, dynamic>? arguments,
}) {
  final Map<String, dynamic> safeArguments =
      arguments ?? const <String, dynamic>{};
  switch (name) {
    case '/':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: HomePage(),
        description: 'home',
      );
    case 'testPage':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: TestPage(
          list: asT<List<int>>(safeArguments['list']),
          testModel: asT<TestModel>(safeArguments['testModel']),
        ),
        description: '测试法法路由',
      );
    default:
      return const FFRouteSettings(name: '404', routeName: '404_page');
  }
}
